collections:
    events:
    press:
    publications:
    deliverables:

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"

permalink: /:categories/:year/:month/:day/:title/

baseurl: https://br0ast.github.io/retestjekyll/
url: https://br0ast.github.io/retestjekyll/

theme: jekyll-theme-minimal
