collections:
    events:
    press:
    publications:
    deliverables:

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"

#baseurl: /
url: https://br0ast.github.io/testjekyll/
